INSERT INTO loan_account_accounts (
    id,
    account_number,
    profile_id,
    loan_product_id,
    idempotency_key,
    initial_principal,
    outstanding_principal,
    credit_limit_at_capture,
    issuance_status,
    performance_status,
    parent_loan_account_id,
    taken_at,
    settled_at,
    repayment_due_at,
    days_past_due,
    last_serviced_at,
    created_at,
    updated_at
) VALUES
(
    'acc_burgundy_001',
    'LN-BURG-0001',
    'prof_burgundy_001',
    'prod_001',
    'burgundy-loan-001',
    5000.0000,
    3500.0000,
    12000,
    'ACTIVE',
    'ACTIVE',
    NULL,
    CURRENT_TIMESTAMP - INTERVAL '40 days',
    NULL,
    CURRENT_TIMESTAMP - INTERVAL '5 days',
    0,
    NULL,
    CURRENT_TIMESTAMP - INTERVAL '40 days',
    CURRENT_TIMESTAMP - INTERVAL '1 day'
),
(
    'acc_burgundy_002',
    'LN-BURG-0002',
    'prof_burgundy_001',
    'prod_002',
    'burgundy-loan-002',
    9000.0000,
    6200.0000,
    15000,
    'ACTIVE',
    'ACTIVE',
    NULL,
    CURRENT_TIMESTAMP - INTERVAL '70 days',
    NULL,
    CURRENT_TIMESTAMP - INTERVAL '32 days',
    0,
    NULL,
    CURRENT_TIMESTAMP - INTERVAL '70 days',
    CURRENT_TIMESTAMP - INTERVAL '1 day'
),
(
    'acc_burgundy_003',
    'LN-BURG-0003',
    'prof_burgundy_001',
    'prod_003',
    'burgundy-loan-003',
    15000.0000,
    10000.0000,
    25000,
    'ACTIVE',
    'ACTIVE',
    NULL,
    CURRENT_TIMESTAMP - INTERVAL '250 days',
    NULL,
    CURRENT_TIMESTAMP - INTERVAL '190 days',
    0,
    NULL,
    CURRENT_TIMESTAMP - INTERVAL '250 days',
    CURRENT_TIMESTAMP - INTERVAL '1 day'
);
